project:
  type: website

website:
  title: "ML Interview Notes"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: notes/index.qmd
        text: Notes
      - href: posts/index.qmd
        text: Blog
  search: true

format:
  html:
    toc: true
    code-fold: false
    code-copy: true
    theme: cosmo

execute:
  freeze: auto
