project:
  type: website

website:
  title: "Minimal ML"
  site-url: "https://threeeyelidds.github.io/minimal-ml/"
  repo-url: "https://github.com/threeeyelidds/minimal-ml"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: notes/index.qmd
        text: Notes
      - href: essays/index.qmd
        text: Essays
  search: true

format:
  html:
    toc: true
    code-fold: false
    code-copy: true
    include-in-header:
      text: |
        <meta name="google-site-verification" content="Ztjr25pGaioeZP-mkoIn_MkNmmsFXWcU6I6W2tEPli0">
    theme: cosmo
    css:
      - styles.css
      - colors.css

execute:
  freeze: auto
